### ISSUE TITLE
Notebook Instance Lifecycle Config timeout

### ISSUE THREAD

**Issue by ranman** [aws-samples/aws-admartech-samples#1]
The lifecycle config in the template referenced by another template in the identity graph solution [here](https://s3.amazonaws.com/aws-neptune-customer-samples/neptune-sagemaker/cloudformation-templates/neptune-sagemaker/neptune-sagemaker-nested-stack.json)

Gave me the following error:

2020-05-13 15:35:37 UTC-0700	NeptuneNotebookInstance	CREATE_FAILED	Notebook Instance Lifecycle Config 'arn:aws:sagemaker:us-west-2:XXX:notebook-instance-lifecycle-config/neptunenotebookinstancelifecycleconfig-7fpg6wxfzxq4' for Notebook Instance 'arn:aws:sagemaker:us-west-2:XXXX:notebook-instance/neptunenotebookinstance-kuhtgb3nwlns' took longer than 5 minutes. Please check your CloudWatch logs for more details if your Notebook Instance has Internet access.

In the template could we just cat the stuff commands into a script, chmod +x it and then nohup that execution? or create a cloudformation wait condition somewhere?

**Comment by beebs-systap** [comment]
@triggan Do you mind taking a look at this one?

**Comment by triggan** [comment]
@ranman - Yep, that's actually a good idea (re: build those items into a shell script).  Just for others that may find this, the referencing template that you mention is part of a Neptune-SageMaker stack that we've created as a foundational stack for multiple use cases.  The original template is located [here](https://github.com/aws-samples/amazon-neptune-samples/blob/master/neptune-sagemaker/cloudformation-templates/neptune-sagemaker/neptune-sagemaker-nested-stack.json).

We've run into some sporadic issues in the past with downloads of both RDF4j and the TinkerPop Gremlin Console using slow mirrors and holding up the notebook install.  While neither of those libraries are directly used for this sample workload, they are useful for troubleshooting.  The RDF4j package is only downloaded, so we previously nohup'd the wget command to fetch that.  The Gremlin Console, however, is actually unzipped and pre-configured for use against the Neptune cluster deployed in this stack.

To your point, I think we should be able to get around some of these slow mirror issues by putting all of those shell commands into a shell script and nohup'ing the entire script.  I'll work back with the team to do that and fix the upstream version of the template.

**Comment by triggan** [comment]
This has now been addressed with the latest PR, PR #7 .  The stack has been modified to use a Neptune Notebook instance and no longer deploys the Gremlin Console or RDF4j libraries (the two that would cause the stack deployment to timeout).  Neptune Notebooks use the [graph-notebook](https://github.com/aws/graph-notebook) libraries that replace the need for most of the functionality required when using either of the former tools.
