### ISSUE TITLE
Visualizations Not Working - Dependency on networkx 2.3

### ISSUE THREAD

**Issue by triggan** [aws-samples/aws-admartech-samples#2]
The current version of the notebooks have visualizations using networkx.  These visualizations are currently not working as the default version for networkx has been upgraded to 2.4 within SageMaker Notebook instances.  The code that generates the visualizations needs to be refactored to support networkx 2.4.  In the meantime, you can downgrade networkx to 2.3 to fix the issues.

**Comment by jbernalvallejo** [comment]
Once networks is downgraded, restart the kernel for the notebook to force it to pick that version up.

**Comment by triggan** [comment]
Addressed this in the latest PR, PR #7 .  The stack has now been moved to use a Neptune Notebook and the remaining `nepytune` libraries have been modified to support the newer version of `networkx` deployed with this stack.
